name: jlexa
description: "JLexa English Learning App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  audioplayers: ^6.1.0
  file_picker: ^8.1.7
  flutter_tts: ^4.2.2
  record: ^7.1.1
  intl: ^0.20.2
  uuid: ^4.5.1
  crypto: ^3.0.7
  dio: ^5.7.0
  flutter_markdown_plus: ^1.0.12
  markdown: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.4
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/dictionary/ecdict-v1.db
    - assets/dictionary/ECDICT-LICENSE.txt
